### ISSUE TITLE
Setup instructions - question about cron

### ISSUE THREAD

**Issue by nickjohnsonm** [guilhemmarchand/nmon-for-splunk#108]
Used the instructions and found the cron wasn't kicking off, looks like it's from this:

chown nmon:nmon /etc/cron.d/nmon-logger

By default the cron.d files need to be owned by root.  It will still run as the nmon user.

**Comment by guilhemmarchand** [comment]
Hello!

We are talking about the nmon-logger right.
Could you precise the flavor ? (rsyslog / syslog-ng / HEC) and the guest Operating System ?

Many thanks,

Guilhem

**Comment by nickjohnsonm** [comment]
This is the info:

rsyslogd 8.26.0, compiled with:
	PLATFORM:				x86_64-redhat-linux-gnu


To be more specific, used the instructions to add some steps to a chef recipe, and found that the nmon-logger cron wasn't starting.  Found that the /etc/cron.d/nmon-logger file was owned by nmon:nmon, once this was changed to root:root then the nmon-logger process was started.

Thanks

**Comment by guilhemmarchand** [comment]
Hello @nickjohnsonm 

Sorry for the long delay to fix it as I've been very busy recently, and again thank you very much for the notice!

You were totally correct, the build spec files for deb and rpm were ok but not the manual instructions.
All fixed now.

Kind regards,

Guilhem
