### ISSUE TITLE
Is it possible to set the host value?

### ISSUE THREAD

**Issue by giovanifss** [guilhemmarchand/nmon-for-splunk#111]
I couldn't find anything related in the documentation, but in splunk forwarder's monitors we can set the host value through the `-host` parameter, and inside the config's stanza we can add:
```
[foo]
host = bar
```  

Is it possible to set the host value in nmon too?

**Comment by guilhemmarchand** [comment]
Hello !

By default, the TA-nmon uses the value returned by the nmon process to override the host value at indexing time (which configuration can be found in default/transforms.conf)

The hostname value retrieved by nmon itself is the value retrieved by the C function on the operating system level.

**You can actually use the following option:**

[https://github.com/guilhemmarchand/TA-nmon/blob/master/TA-nmon/default/nmon.conf]

```
# This option can be used to force the technical add-on to use the Splunk configured value of the server hostname
# If for some reason, you need to use the Splunk host value instead of the system real hostname value, set this value to "1"

# We will search for the value of host=<value> in $SPLUNK_HOME/etc/system/local/inputs.conf
# If no value can be found, or if the file does not exist, we will fallback to the normal behavior

# Default is use system hostname

# FQDN management in nmon2csv.pl/nmon2csv.py: The --fqdn option is not compatible with the host name override, if the override_sys_hostname
# is activated, the --fqdn argument will have no effect

override_sys_hostname="0"
```

If you create a TA-nmon/local/nmon.conf containing

override_sys_hostname="1"

The TA-nmon will use the value retrieved from $SPLUNK_HOME/etc/system/local/inputs.conf to define the hostname value, which overrides the one retrieved by nmon.

Does this replies to your needs ?

**Comment by giovanifss** [comment]
Yes, thank you!

**Comment by giovanifss** [comment]
@guilhemmarchand  Do you know why this does not work for `fifo_consumer`, `nmon_collect` and `nmon_cleaner`?
The only plugin that is sending the corret host value is `perfdata`.

**Comment by guilhemmarchand** [comment]
Hello,

Yes, there some minor evolutions required to make it applied to other sourcetypes.
Actually, these sourcetypes are mainly internal application data, and their content is indexed from stdout and/or calls to the “hostname” command.

I’ve done it recently for the future release of the apps (which relies on the metric store)
I will backport these changes in the TA-NMON promptly.

I will ping you once ready.

Regards 

Guilhem

**Comment by giovanifss** [comment]
@guilhemmarchand Ok, thank you. If you have any task that can be performed without a deep understand of the project, I can help.

**Comment by guilhemmarchand** [comment]
@giovanifss Thank you ;-) Testing will always be very welcomed!

**Comment by guilhemmarchand** [comment]
@giovanifss Actually, could you be more specific when you say that it does not work for other sourcetypes ?

Just ran a verification, having a forwarder with host value in $SPLUNK_HOME/etc/system/local/inputs.conf that differs from the hostname value of the system, and as far as I can see all the sourcetypes get the proper host Metadata:

- nmon_clean
- nmon_collect 
- nmon_config 
- nmon_data 
- nmon_processing

However, in the content of the message logged, it will contain the real host name value from the host.
Is this what you were referring to ?

KInd regards,

Guilhem

**Comment by giovanifss** [comment]
@guilhemmarchand Yes, the logged message in the splunk (server/cloud) has the host specified in $SPLUNK_HOME/etc/system/local/inputs.conf only in perfdata:
![screenshot from 2018-03-23 11-54-34](https://user-images.githubusercontent.com/11573379/37836347-fc38c692-2e90-11e8-98ac-4eeebe8ca254.png)

The others get the machine hostname:
![screenshot from 2018-03-23 11-54-03](https://user-images.githubusercontent.com/11573379/37836349-fc5d5a3e-2e90-11e8-8447-b1956c31c69d.png)

The relevant configuration that I've put inside inputs.conf is:
```
[defaults]
host = <value>
```

**Comment by guilhemmarchand** [comment]
Hi @giovanifss 

Could you give a test to the version 1.3.33 in testing branch:

[https://github.com/guilhemmarchand/TA-nmon/tree/testing](https://github.com/guilhemmarchand/TA-nmon/tree/testing)

This is fixed in the new version.

Kind regards,

Guilhem

**Comment by giovanifss** [comment]
Sure! I will test it.

**Comment by giovanifss** [comment]
@guilhemmarchand It didn't work, the logged messages are still logging the real host name. Steps that I took:
- Build a nmon tgz through `build.sh` in `testing` branch (version 1.3.33);
- Install universal forwarder and TA-nmon on the virtual machine;
- Setup configuration of UF and TA-nmon:
    - Add `override_sys_hostname="1"` in `SPLUNK_HOME/etc/apps/TA-nmon/local/nmon.conf`
    - Add `host = my.host` in `/etc/system/local/inputs.conf` inside `[defaults]`;
- Start universal forwarder

`/etc/hostname` = `virtualbox-VirtualBox`

![screenshot from 2018-04-03 14-40-45](https://user-images.githubusercontent.com/11573379/38265723-0f4ed720-374d-11e8-9f20-b09103d6156c.png)

**Comment by guilhemmarchand** [comment]
Hello @giovanifss 

Thanks for your test.

Right, to me it looks all good, so just to be sure:

**$SPLUNK_HOME/etc/system/local/inputs.conf configuration**

When you start Splunk for the first time, Splunk automatically creates the inpputs.conf file containing the name of the host retrieved from the system, for example the following host name is "forwarder1":

```
cat /opt/splunkforwarder/etc/system/local/inputs.conf 

[default]
host = forwarder1

```

Once I change this value to something else, in my test "test-client" **AND I restart Splunk (did you restart Splunk ? This is mandatory)**

This value will used by Splunk to setup the host Metadata by default when forwarding an event. (caution you should only have 1 host value in this file obviously)

![image](https://user-images.githubusercontent.com/7503059/38299693-b64665f2-37f2-11e8-896c-1d495ef639e5.png)

![image](https://user-images.githubusercontent.com/7503059/38299698-c379b850-37f2-11e8-8d18-9cbbfd428626.png)

![image](https://user-images.githubusercontent.com/7503059/38299738-d378e3ca-37f2-11e8-8638-1b9fa65e3c78.png)

![image](https://user-images.githubusercontent.com/7503059/38299749-e108b1aa-37f2-11e8-8b3c-8e4325fbf647.png)

![image](https://user-images.githubusercontent.com/7503059/38299759-ed1941bc-37f2-11e8-8484-72cd5f4fd409.png)

Does the problem comes from a lack of restart of the instance after inputs.conf modification ?

The scripts coming from the TA-nmon do not need the restart but Splunk does.

Guilhem

**Comment by giovanifss** [comment]
In my installation script the configurations are setted before splunk is started, and splunk is restarted in later steps. Checking the configuration file after start showed that it is exactly the one that I've setted and contains only one host.

I will re-check everything and run again. Also, I will manually install and restart splunk to make sure those steps are fulfilled. Thanks.

**Comment by guilhemmarchand** [comment]
@giovanifss 

Thanks

I see, please double check, because the nmon_processing, nmon_collect and nmon_clean are indexed from the stdout and nothing rewrites the host Meta. (only nmon_data and nmon_config do rewrite the host value)
Which means that the host value is the one automatically set by Splunk

Check that the _internal events are coming correctly with the host value configured in your inputs.conf

Regards,

Guilhem

**Comment by giovanifss** [comment]
@guilhemmarchand Yeah, I've re-checked everything and it still does not work.

The _internal events does not seem right:
![internal](https://user-images.githubusercontent.com/11573379/38327283-3e154b76-381e-11e8-94ff-aa754c7dd49b.png)

But the weird thing is that the host value specified in the UF configuration works fine besides not having anything about it in _internal:
![authssh](https://user-images.githubusercontent.com/11573379/38327343-5f1e4f8e-381e-11e8-8e48-082ed01da9fe.png)
![edited_file](https://user-images.githubusercontent.com/11573379/38327355-68973e40-381e-11e8-981b-1d01c3b8cd84.png)

And the specified host in nmon only works in perfdata:
![perfdata-nmon](https://user-images.githubusercontent.com/11573379/38327382-79990dd6-381e-11e8-9753-4cdb36336522.png)

Nothing shows up for anything different than perdata:
![not-perfdata](https://user-images.githubusercontent.com/11573379/38327421-8f7c627e-381e-11e8-9419-ff4bcf588418.png)

While others use the /etc/hostname:
![vbox-notperf](https://user-images.githubusercontent.com/11573379/38327431-97beaa96-381e-11e8-8ab8-e24fb73e65af.png)

Do you think that the fact that I'm using splunkcloud has anything to do with it? I've installed only the TA-nmon add on in the UF, I didn't update anything on the server side.

**Comment by guilhemmarchand** [comment]
Hi @giovanifss 

The _internal events forwarding is THE first and THE only one to check before anything, if you have a problem with that then no need to got further, you have a Splunk configuration error.

The reason why others are working fine is probably (sure for nmon_data) that the host Meta is being overridden by a transforms stanza.

**Can you run a btool please:**

`/opt/splunkforwarder/bin/splunk btool inputs list --debug 
`
Then search for the "host" key definition and verify where the configuration stanza comes from.

Your "/opt/splunkforwarder/etc/system/local/inputs.conf" and should look like that:

```
[default]
host = forwarder1

```
And this should match the value you have from btool.

Guilhem

**Comment by giovanifss** [comment]
@guilhemmarchand You are right, It was a misconfiguration in the UF. The stanza was:
```
[defaults]
host = myhost
````
When it should be ```[default]```. Sorry for this, always embarrassing.

I can now confirm that everything is working fine :+1:

**Comment by guilhemmarchand** [comment]
@giovanifss No problem at all ;-)

Great many thanks, the new version is ready to go in release, will be published to Splunk base very soon.

**Comment by giovanifss** [comment]
Great. Thank you!
