### ISSUE TITLE
Top processes 

### ISSUE THREAD

**Issue by diasgiri** [guilhemmarchand/nmon-for-splunk#120]
Hello,
         Is there a way to check the top processes of java with specific process ids sorted on the basis of cpu consumption and also with memory consumptions?

**Comment by diasgiri** [comment]
Hello,
       Basically looking for a dashboard which gives you the data for CPU, memory and IO arranged with the process IDs. For example we have the bubble graph for the memory, cpu exhibiting which command is consuming the more memory and cpu, it will be great when I click on that big bubble it would take me to a graph which gives more granular data based on the process ids. Eg: if java command is the big bubble then clicking on that takes you to another time series graph with PIDs of various java process.

**Comment by guilhemmarchand** [comment]
closed for inactivity, please reach out if needed.
