### ISSUE TITLE
TA-mon Not Working on Ubuntu 20.04

### ISSUE THREAD

**Issue by eljefe-3** [guilhemmarchand/nmon-for-splunk#126]
I just started using this amazing application, but am running into some issues.  I installed the TA according to documentation which was just extracting the app into the appropriate directory.  Is this TA compatible with Ubuntu 20.04?   

message from "/opt/splunk/etc/apps/TA-nmon/bin/nmon_helper.sh" /opt/splunk/var/log/nmon/bin/linux/generic/nmon_linux_x86_64: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

ERROR, nmon binary returned a non 0 code while trying to start, please verify error traces in splunkd log (missing shared libraries?)

**Comment by eljefe-3** [comment]
installed nmon on Ubuntu 20.04 and everything appears to be working.

**Comment by guilhemmarchand** [comment]
Hi @eljefe-3 !

The legacy Nmon is super seed by the Metric store versions, called Metricator:

https://splunkbase.splunk.com/app/3948/

I need to archive these repos and their apps on Splunk base too, by the way, the reently release of this Addon includes the missing Nmon binary for Ubuntu 20.

You will find docs here:

https://www.octamis.com/metricator-docs/
