### ISSUE TITLE
Dashboard still points to /dj/ on 1.7.4

### ISSUE THREAD

**Issue by brandonganem** [guilhemmarchand/nmon-for-splunk#54]
Hi, with Splunk 6.4.3 & NMON 1.7.4 the following dashboards still point to Django:
"TOP CPU/MEMORY > Main hosts Usage in PieChart"
"TOP Processes >> Main process usage"

Both are located under Linux > DASHBOARDS.

**Comment by guilhemmarchand** [comment]
Hi, thank you for reporting this, that's correct, there are some out of date links still pointing to removed django dashboards.

This will be corrected very soon with 1.7.6

**Comment by guilhemmarchand** [comment]
V1.7.6 is out officially and solves this issue.
