### ISSUE TITLE
ERROR KVStoreLookup

### ISSUE THREAD

**Issue by mightaswelby** [guilhemmarchand/nmon-for-splunk#65]
I am seeing the following KVStoreLookup error after the last Splunk restart.  This just started with no changes to the environment.  Is the best solution to this to redeploy the NMON app in Splunk?

03-07-2017 10:42:50.316 -0600 ERROR KVStoreLookup - External command based lookup 'nmon_inventory' is not available because KV Store initialization has failed. Please contact your system administrator.
03-07-2017 10:42:50.316 -0600 ERROR KVStoreLookup - Failed to execute KV Store lookups: External command based lookup 'nmon_inventory' is not available because KV Store initialization has failed. Please contact your system administrator.

**Comment by guilhemmarchand** [comment]
Hi,

The "nmon_inventory" lookup table is a KVstore based lookup.
As well, note that this is a replicated KVstore between search heads and indexers.

If after the initial deployment, and after a proper Splunk restart (a "pure" Splunk restart for standalone instances, a automatic rolling restart for search heads and indexers in cluster) you have a message failure about the KV store you probably have a different issue that makes your instance unable to properly start MongoDB.

I would suggest stopping your instance, ensuring that you do have any Splunk process running (including the mongo process) and start.

Can you tell me more about your deployment ?

- Standalone ? Clusters ?
- Version ?

**Comment by mightaswelby** [comment]
Thanks Marchand.  It's a standalone server instance having issue on the 
latest verion of 6.5.2.  After doing a little more investigating I did 
notice the KVstore errors in the mongo.log and splunkd.log.  I've filed 
an issues ticket to Splunk to help investigate.  Looks like the nmon 
error is a victim of the KVstore issue.  Thanks for the prompt response.

------ Original Message ------
